# Generated by Django 3.2.9 on 2022-12-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('totalfees', models.FloatField(default='300000')),
                ('paidfees', models.FloatField()),
                ('feebal', models.FloatField(default='0')),
            ],
        ),
    ]
